-- Generated by nwg-displays on 2026-09-07 at 10:10:34. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2880x1920@120.0",
    position = "1301x1600",
    scale = 2.0,
    vrr = 0
})
hl.monitor({
    output = "DP-1",
    mode = "3840x1600@119.98",
    position = "0x0",
    scale = 1.0,
    vrr = 0
})
