# set-option -g default-shell /usr/bin/fish
# Remap prefix
unbind C-b
set-option -g prefix C-x
bind-key C-a send-prefix
# Reload configuration
bind r source-file ~/.config/tmux/tmux.conf
# Pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# Resize panes
bind -n C-h resize-pane -L 5
bind -n C-j resize-pane -D 5
bind -n C-k resize-pane -U 5
bind -n C-l resize-pane -R 5
setw -g mode-keys vi
set -g status-position top
# Disable auto-renaming of windows
set-option -g allow-rename off
# enable mouse support
set -g mouse on
# set history size
set -g history-limit 8192

# Theming
# General
set -g status on
set -g status-interval 5
set -g status-style "bg=default,fg=#D8B64A"

# Left Side
set -g status-left-length 30
set -g status-left "[#S]"

# Right Side
set -g status-right-length 40
set -g status-right "[HIVE]"

# Middle
set -g status-justify centre

# Inactive Windows
setw -g window-status-format " #I:#W "

# Active window
setw -g window-status-current-format " [#I:#W] "


# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

run '~/.tmux/plugins/tpm/tpm'
